export const rates = {
  "success": true,
  "timestamp": 1524642843,
  "base": "EUR",
  "date": "2018-04-25",
  "rates": {
    "AED": 4.479518,
    "AFN": 85.447783,
    "ALL": 128.080497,
    "AMD": 585.058087,
    "ANG": 2.171403,
    "AOA": 270.139413,
    "ARS": 24.706038,
    "AUD": 1.610034,
    "AWG": 2.171264,
    "AZN": 2.073073,
    "BAM": 1.958528,
    "BBD": 2.439623,
    "BDT": 101.903035,
    "BGN": 1.953398,
    "BHD": 0.459619,
    "BIF": 2135.865119,
    "BMD": 1.219811,
    "BND": 1.588437,
    "BOB": 8.368104,
    "BRL": 4.236159,
    "BSD": 1.219811,
    "BTC": 0.00013,
    "BTN": 81.056455,
    "BWP": 11.929383,
    "BYN": 2.439658,
    "BYR": 23908.300962,
    "BZD": 2.436934,
    "CAD": 1.568263,
    "CDF": 1909.616956,
    "CHF": 1.198001,
    "CLF": 0.026751,
    "CLP": 730.065135,
    "CNY": 7.708478,
    "COP": 3393.637064,
    "CRC": 685.350935,
    "CUC": 1.219811,
    "CUP": 32.324999,
    "CVE": 110.283142,
    "CZK": 25.445138,
    "DJF": 215.69923,
    "DKK": 7.449503,
    "DOP": 60.319669,
    "DZD": 139.303662,
    "EGP": 21.55387,
    "ERN": 18.284846,
    "ETB": 33.203262,
    "EUR": 1,
    "FJD": 2.488954,
    "FKP": 0.871796,
    "GBP": 0.874556,
    "GEL": 3.011837,
    "GGP": 0.874528,
    "GHS": 5.417131,
    "GIP": 0.872186,
    "GMD": 57.06277,
    "GNF": 10978.301074,
    "GTQ": 8.948545,
    "GYD": 250.646816,
    "HKD": 9.573448,
    "HNL": 28.742428,
    "HRK": 7.416941,
    "HTG": 79.495098,
    "HUF": 312.820616,
    "IDR": 16967.574815,
    "ILS": 4.356922,
    "IMP": 0.874528,
    "INR": 81.396782,
    "IQD": 1444.256548,
    "IRR": 51232.073611,
    "ISK": 122.408059,
    "JEP": 0.874528,
    "JMD": 151.220005,
    "JOD": 0.863636,
    "JPY": 133.148498,
    "KES": 121.798153,
    "KGS": 83.484613,
    "KHR": 4891.442676,
    "KMF": 486.704442,
    "KPW": 1097.830305,
    "KRW": 1317.70155,
    "KWD": 0.366557,
    "KYD": 1.000852,
    "KZT": 398.707495,
    "LAK": 10108.57594,
    "LBP": 1835.816127,
    "LKR": 191.815553,
    "LRD": 159.929457,
    "LSL": 15.040249,
    "LTL": 3.71884,
    "LVL": 0.756954,
    "LYD": 1.626502,
    "MAD": 11.26679,
    "MDL": 20.084251,
    "MGA": 3872.901071,
    "MKD": 61.246723,
    "MMK": 1626.008132,
    "MNT": 2915.349342,
    "MOP": 9.860351,
    "MRO": 429.373335,
    "MUR": 41.571171,
    "MVR": 18.992495,
    "MWK": 875.824179,
    "MXN": 23.019548,
    "MYR": 4.770656,
    "MZN": 71.968887,
    "NAD": 15.140257,
    "NGN": 436.691738,
    "NIO": 38.140328,
    "NOK": 9.674836,
    "NPR": 129.190217,
    "NZD": 1.721637,
    "OMR": 0.469388,
    "PAB": 1.219811,
    "PEN": 3.93881,
    "PGK": 3.963781,
    "PHP": 63.84474,
    "PKR": 141.010181,
    "PLN": 4.214937,
    "PYG": 6757.632355,
    "QAR": 4.439864,
    "RON": 4.649554,
    "RSD": 117.640678,
    "RUB": 75.209417,
    "RWF": 1031.728571,
    "SAR": 4.573923,
    "SBD": 9.474885,
    "SCR": 16.38228,
    "SDG": 22.017836,
    "SEK": 10.40954,
    "SGD": 1.619677,
    "SHP": 0.872153,
    "SLL": 9307.159721,
    "SOS": 687.973888,
    "SRD": 9.050673,
    "STD": 24506.251495,
    "SVC": 10.673274,
    "SYP": 628.178385,
    "SZL": 15.141546,
    "THB": 38.460651,
    "TJS": 10.837051,
    "TMT": 4.159556,
    "TND": 2.949018,
    "TOP": 2.726398,
    "TRY": 4.971339,
    "TTD": 8.247167,
    "TWD": 36.232053,
    "TZS": 2777.510437,
    "UAH": 32.032383,
    "UGX": 4503.543612,
    "USD": 1.219811,
    "UYU": 34.31329,
    "UZS": 9804.842773,
    "VEF": 81446.798456,
    "VND": 27771.443265,
    "VUV": 129.324388,
    "WST": 3.081972,
    "XAF": 655.380236,
    "XAG": 0.073361,
    "XAU": 0.000921,
    "XCD": 3.295704,
    "XDR": 0.844042,
    "XOF": 655.380236,
    "XPF": 119.382691,
    "YER": 304.769854,
    "ZAR": 15.144079,
    "ZMK": 10979.76386,
    "ZMW": 11.6368,
    "ZWL": 393.212277
  }
}

export const currencies = [
  {
    code: "AED",
    name: 'UAE dirhams',
    flag: '',
  },
  {
    code: "AFN",
    name: 'Afghanistan Afghanis',
    flag: '',
  },
  {
    code: "ALL",
    name: 'Albanian lekë',
    flag: '',
  },
  {
    code: "AMD",
    name: 'Armenian drams',
    flag: '',
  },
  {
    code: "ANG",
    name: 'Netherlands Antillean Guilder',
    flag: '',
  },
  {
    code: "AOA",
    name: 'Angolan Kwanza',
    flag: '',
  },
  {
    code: "ARS",
    name: 'Argentine pesos',
    flag: '',
  },
  {
    code: "AUD",
    name: 'Australian dollars',
    flag: '',
  },
  {
    code: "AWG",
    name: 'Aruban Florin',
    flag: '',
  },
  {
    code: "AZN",
    name: 'Azerbaijani manats',
    flag: '',
  },
  {
    code: "BAM",
    name: 'Bosnia-Herz conv marks',
    flag: '',
  },
  {
    code: "BBD",
    name: 'Barbadian Dollar',
    flag: '',
  },
  {
    code: "BDT",
    name: 'Bangladeshi takas',
    flag: '',
  },
  {
    code: "BGN",
    name: 'Bulgarian leva',
    flag: '',
  },
  {
    code: "BHD",
    name: 'Bahraini dinars',
    flag: '',
  },
  {
    code: "BIF",
    name: 'Burundian francs',
    flag: '',
  },
  {
    code: "BMD",
    name: 'Bermudan Dollar',
    flag: '',
  },
  {
    code: "BND",
    name: 'Brunei dollars',
    flag: '',
  },
  {
    code: "BOB",
    name: 'Bolivian bolivianos',
    flag: '',
  },
  {
    code: "BRL",
    name: 'Brazilian reals',
    flag: '',
  },
  {
    code: "BSD",
    name: 'Bahamian Dollar',
    flag: '',
  },
  {
    code: "BTC",
    name: 'Bitcoin',
    flag: '',
  },
  {
    code: "BTN",
    name: 'Bhutanese Ngultrum',
    flag: '',
  },
  {
    code: "BWP",
    name: 'Botswanan pulas',
    flag: '',
  },
  {
    code: "BYN",
    name: 'Belarusian ruble',
    flag: '',
  },
  {
    code: "BYR",
    name: 'Belarusian rubles',
    flag: '',
  },
  {
    code: "BZD",
    name: 'Belize dollars',
    flag: '',
  },
  {
    code: "CAD",
    name: 'Canadian dollars',
    flag: '',
  },
  {
    code: "CDF",
    name: 'Congolese francs',
    flag: '',
  },
  {
    code: "CHF",
    name: 'Swiss francs',
    flag: '',
  },
  {
    code: "CLF",
    name: 'Chilean Unit Of Account',
    flag: '',
  },
  {
    code: "CLP",
    name: 'Chilean pesos',
    flag: '',
  },
  {
    code: "CNY",
    name: 'Chinese yuan',
    flag: '',
  },
  {
    code: "COP",
    name: 'Colombian pesos',
    flag: '',
  },
  {
    code: "CRC",
    name: 'Costa Rican colóns',
    flag: '',
  },
  {
    code: "CUC",
    name: 'Cuban Convertible Peso',
    flag: '',
  },
  {
    code: "CUP",
    name: 'Cuban Peso',
    flag: '',
  },
  {
    code: "CVE",
    name: 'Cape Verdean escudos',
    flag: '',
  },
  {
    code: "CZK",
    name: 'Czech Republic korunas',
    flag: '',
  },
  {
    code: "DJF",
    name: 'Djiboutian francs',
    flag: '',
  },
  {
    code: "DKK",
    name: 'Danish kroner',
    flag: '',
  },
  {
    code: "DOP",
    name: 'Dominican pesos',
    flag: '',
  },
  {
    code: "DZD",
    name: 'Algerian dinars',
    flag: '',
  },
  {
    code: "EGP",
    name: 'Egyptian pounds',
    flag: '',
  },
  {
    code: "ERN",
    name: 'Eritrean nakfas',
    flag: '',
  },
  {
    code: "ETB",
    name: 'Ethiopian birrs',
    flag: '',
  },
  {
    code: "EUR",
    name: 'Euros',
    flag: '',
  },
  {
    code: "FJD",
    name: 'Fijian Dollar',
    flag: '',
  },
  {
    code: "FKP",
    name: 'United Arab Emirates',
    flag: '',
  },
  {
    code: "GBP",
    name: 'British pounds sterling',
    flag: '',
  },
  {
    code: "GEL",
    name: 'Georgian laris',
    flag: '',
  },
  {
    code: "GGP",
    name: 'Guernsey Pound',
    flag: '',
  },
  {
    code: "GHS",
    name: 'Ghanaian cedis',
    flag: '',
  },
  {
    code: "GIP",
    name: 'Gibraltar Pound',
    flag: '',
  },
  {
    code: "GMD",
    name: 'Gambian Dalasi',
    flag: '',
  },
  {
    code: "GNF",
    name: 'Guinean francs',
    flag: '',
  },
  {
    code: "GTQ",
    name: 'Guatemalan quetzals',
    flag: '',
  },
  {
    code: "GYD",
    name: 'Guyanaese Dollar',
    flag: '',
  },
  {
    code: "HKD",
    name: 'Hong Kong dollars',
    flag: '',
  },
  {
    code: "HNL",
    name: 'Honduran lempiras',
    flag: '',
  },
  {
    code: "HRK",
    name: 'Croatian kunas',
    flag: '',
  },
  {
    code: "HTG",
    name: 'Haitian Gourde',
    flag: '',
  },
  {
    code: "HUF",
    name: 'Hungarian forints',
    flag: '',
  },
  {
    code: "IDR",
    name: 'Indonesian rupiahs',
    flag: '',
  },
  {
    code: "ILS",
    name: 'Israeli new sheqels',
    flag: '',
  },
  {
    code: "IMP",
    name: 'Manx pound',
    flag: '',
  },
  {
    code: "INR",
    name: 'Indian rupees',
    flag: '',
  },
  {
    code: "IQD",
    name: 'Iraqi dinars',
    flag: '',
  },
  {
    code: "IRR",
    name: 'Iranian rials',
    flag: '',
  },
  {
    code: "ISK",
    name: 'Icelandic krónur',
    flag: '',
  },
  {
    code: "JEP",
    name: 'Jersey Pound ',
    flag: '',
  },
  {
    code: "JMD",
    name: 'Jamaican dollars',
    flag: '',
  },
  {
    code: "JOD",
    name: 'Jordanian dinars',
    flag: '',
  },
  {
    code: "JPY",
    name: 'Japanese yen',
    flag: '',
  },
  {
    code: "KES",
    name: 'Kenyan shillings',
    flag: '',
  },
  {
    code: "KGS",
    name: 'Kyrgystani Som',
    flag: '',
  },
  {
    code: "KHR",
    name: 'Cambodian riels',
    flag: '',
  },
  {
    code: "KMF",
    name: 'Comorian francs',
    flag: '',
  },
  {
    code: "KPW",
    name: 'North Korean Won',
    flag: '',
  },
  {
    code: "KRW",
    name: 'South Korean won',
    flag: '',
  },
  {
    code: "KWD",
    name: 'Kuwaiti dinars',
    flag: '',
  },
  {
    code: "KYD",
    name: 'Cayman Islands Dollar ',
    flag: '',
  },
  {
    code: "KZT",
    name: 'Kazakhstani tenges',
    flag: '',
  },
  {
    code: "LAK",
    name: 'Laotian Kip',
    flag: '',
  },
  {
    code: "LBP",
    name: 'Lebanese pounds',
    flag: '',
  },
  {
    code: "LKR",
    name: 'Sri Lankan rupees',
    flag: '',
  },
  {
    code: "LRD",
    name: 'Liberian Dollar',
    flag: '',
  },
  {
    code: "LSL",
    name: 'Lesotho Loti',
    flag: '',
  },
  {
    code: "LTL",
    name: 'Lithuanian litai',
    flag: '',
  },
  {
    code: "LVL",
    name: 'Latvian lati',
    flag: '',
  },
  {
    code: "LYD",
    name: 'Libyan dinars',
    flag: '',
  },
  {
    code: "MAD",
    name: 'Moroccan dirhams',
    flag: '',
  },
  {
    code: "MDL",
    name: 'Moldovan lei',
    flag: '',
  },
  {
    code: "MGA",
    name: 'Malagasy Ariaries',
    flag: '',
  },
  {
    code: "MKD",
    name: 'Macedonian denari',
    flag: '',
  },
  {
    code: "MMK",
    name: 'Myanma kyats',
    flag: '',
  },
  {
    code: "MNT",
    name: 'Mongolia Tughrik',
    flag: '',
  },
  {
    code: "MOP",
    name: 'Macanese patacas',
    flag: '',
  },
  {
    code: "MRO",
    name: 'Mauritanian Ouguiya',
    flag: '',
  },
  {
    code: "MUR",
    name: 'Mauritian rupees',
    flag: '',
  },
  {
    code: "MVR",
    name: 'Maldivian Rufiyaa',
    flag: '',
  },
  {
    code: "MWK",
    name: 'Malawian Kwacha',
    flag: '',
  },
  {
    code: "MXN",
    name: 'Mexican pesos',
    flag: '',
  },
  {
    code: "MYR",
    name: 'Malaysian Ringgit',
    flag: '',
  },
  {
    code: "MZN",
    name: 'Mozambican Metical',
    flag: '',
  },
  {
    code: "NAD",
    name: 'Namibian Dollar',
    flag: '',
  },
  {
    code: "NGN",
    name: 'Nigerian Naira',
    flag: '',
  },
  {
    code: "NIO",
    name: 'Nicaraguan Córdoba',
    flag: '',
  },
  {
    code: "NOK",
    name: 'Norwegian Krone',
    flag: '',
  },
  {
    code: "NPR",
    name: 'Nepalese Rupee',
    flag: '',
  },
  {
    code: "NZD",
    name: 'New Zealand Dollar',
    flag: '',
  },
  {
    code: "OMR",
    name: 'Omani Rial',
    flag: '',
  },
  {
    code: "PAB",
    name: 'Panamanian Balboa',
    flag: '',
  },
  {
    code: "PEN",
    name: 'Peruvian Nuevo Sol',
    flag: '',
  },
  {
    code: "PGK",
    name: 'Papua New Guinean Kina',
    flag: '',
  },
  {
    code: "PHP",
    name: 'Philippine Peso',
    flag: '',
  },
  {
    code: "PKR",
    name: 'Pakistani Rupee',
    flag: '',
  },
  {
    code: "PLN",
    name: 'Polish Zloty',
    flag: '',
  },
  {
    code: "PYG",
    name: 'Paraguayan Guarani',
    flag: '',
  },
  {
    code: "QAR",
    name: 'Qatari Rial',
    flag: '',
  },
  {
    code: "RON",
    name: "Romanian Leu",
    flag: '',
  },
  {
    code: "RSD",
    name: 'Serbian Dinar',
    flag: '',
  },
  {
    code: "RUB",
    name: 'Russian Ruble',
    flag: '',
  },
  {
    code: "RWF",
    name: 'Rwandan Franc',
    flag: '',
  },
  {
    code: "SAR",
    name: 'Saudi Riyal',
    flag: '',
  },
  {
    code: "SBD",
    name: 'Solomon Islands Dollar',
    flag: '',
  },
  {
    code: "SCR",
    name: 'Seychellois Rupee',
    flag: '',
  },
  {
    code: "SDG",
    name: 'Sudanese Pound',
    flag: '',
  },
  {
    code: "SEK",
    name: 'Swedish Krona',
    flag: '',
  },
  {
    code: "SGD",
    name: 'Singapore Dollar',
    flag: '',
  },
  {
    code: "SHP",
    name: 'Saint Helena Pound',
    flag: '',
  },
  {
    code: "SLL",
    name: 'Sierra Leonean Leone',
    flag: '',
  },
  {
    code: "SOS",
    name: 'Somali Shilling',
    flag: '',
  },
  {
    code: "SRD",
    name: 'Surinamese Dollar',
    flag: '',
  },
  {
    code: "STD",
    name: 'São Tomé & Príncipe Dobra',
    flag: '',
  },
  {
    code: "SVC",
    name: 'Salvadoran Colón',
    flag: '',
  },
  {
    code: "SYP",
    name: 'Syrian Pound',
    flag: '',
  },
  {
    code: "SZL",
    name: 'Swazi Lilangeni',
    flag: '',
  },
  {
    code: "THB",
    name: 'Thai Baht',
    flag: '',
  },
  {
    code: "TJS",
    name: 'Tajikistani Somoni',
    flag: '',
  },
  {
    code: "TMT",
    name: 'Turkmenistani Manat',
    flag: '',
  },
  {
    code: "TND",
    name: 'Tunisian Dinar',
    flag: '',
  },
  {
    code: "TOP",
    name: 'Tongan Paʻanga',
    flag: '',
  },
  {
    code: "TRY",
    name: 'Turkish Lira',
    flag: '',
  },
  {
    code: "TTD",
    name: 'Trinidad & Tobago Dollar',
    flag: '',
  },
  {
    code: "TWD",
    name: 'New Taiwan Dollar',
    flag: '',
  },
  {
    code: "TZS",
    name: 'Tanzanian Shilling',
    flag: '',
  },
  {
    code: "UAH",
    name: 'Ukrainian Hryvnia',
    flag: '',
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    flag: '',
  },
  {
    code: "USD",
    name: 'USA dollars',
    flag: '',
  },
  {
    code: "UYU",
    name: 'Uruguayan Peso',
    flag: '',
  },
  {
    code: "UZS",
    name: 'Uzbekistan Som',
    flag: '',
  },
  {
    code: "VEF",
    name: 'Venezuelan Bolívar',
    flag: '',
  },
  {
    code: "VND",
    name: 'Vietnamese Dong',
    flag: '',
  },
  {
    code: "VUV",
    name: 'Vanuatu Vatu',
    flag: '',
  },
  {
    code: "WST",
    name: 'Samoa Tala',
    flag: '',
  },
  {
    code: "XAF",
    name: 'Central African CFA Franc',
    flag: '',
  },
  {
    code: "XAG",
    name: '',
    flag: '',
  },
  {
    code: "XAU",
    name: 'Gold Ounces',
    flag: '',
  },
  {
    code: "XCD",
    name: 'East Caribbean Dollar',
    flag: '',
  },
  {
    code: "XDR",
    name: '',
    flag: '',
  },

  {
    code: "XOF",
    name: 'West African CFA Franc',
    flag: '',
  },
  {
    code: "XPF",
    name: 'CFP Franc',
    flag: '',
  },
  {
    code: "YER",
    name: 'Yemeni Rial',
    flag: '',
  },
  {
    code: "ZAR",
    name: 'South African Rand',
    flag: '',
  },
  {
    code: "ZMK",
    name: 'Zambian Kwacha',
    flag: '',
  },
  {
    code: "ZMW",
    name: 'Uruguayan Peso',
    flag: '',
  },
  {
    code: "ZWL",
    name: 'Yemeni Rial',
    flag: '',
  },
]

export const check = {
  SGD: 1.619677,
  SHP: 0.872153,
  SLL: 9307.159721,
  SOS: 687.973888,
  SRD: 9.050673,
}